# Generated by Django 5.1.1 on 2024-09-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0010_alter_employee_position_alter_invitation_invited_by_and_more",
        ),
        ("tasks", "0008_alter_task_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="employees.team"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tasks",
                to="tasks.tasktype",
            ),
        ),
    ]
